# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  sourceFolder: 'files'


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureFileCopy@6
  inputs:
    SourcePath: '$(Build.SourcesDirectory)/$(sourceFolder)'
    azureSubscription: 'Azure subscription 1(ddc45bc2-7a34-4943-8d1b-4aa187194509)'
    Destination: 'AzureBlob'
    storage: 'myblobstoragemanju9676'
    ContainerName: 'samplefiles'
    BlobPrefix: ''


